metadata:
  name: dag-nested-m5kw8
  generateName: dag-nested-
  namespace: argo
  uid: 9ffc54ae-4acd-4917-b602-7cabbb0ea022
  resourceVersion: '9617'
  generation: 14
  creationTimestamp: '2024-03-14T09:06:43Z'
  labels:
    workflows.argoproj.io/completed: 'true'
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
    workflows.argoproj.io/phase: Succeeded
  annotations:
    workflows.argoproj.io/pod-name-format: v2
  managedFields:
    - manager: argo
      operation: Update
      apiVersion: argoproj.io/v1alpha1
      time: '2024-03-14T09:06:43Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:workflows.argoproj.io/creator': {}
        'f:spec': {}
    - manager: workflow-controller
      operation: Update
      apiVersion: argoproj.io/v1alpha1
      time: '2024-03-14T09:09:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:workflows.argoproj.io/pod-name-format': {}
          'f:labels':
            'f:workflows.argoproj.io/completed': {}
            'f:workflows.argoproj.io/phase': {}
        'f:status': {}
spec:
  templates:
    - name: echo
      inputs:
        parameters:
          - name: message
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'alpine:3.7'
        command:
          - echo
          - '{{inputs.parameters.message}}'
        resources: {}
    - name: diamond
      inputs: {}
      outputs: {}
      metadata: {}
      dag:
        tasks:
          - name: A
            template: nested-diamond
            arguments:
              parameters:
                - name: message
                  value: A
          - name: B
            template: nested-diamond
            arguments:
              parameters:
                - name: message
                  value: B
            depends: A
          - name: C
            template: nested-diamond
            arguments:
              parameters:
                - name: message
                  value: C
            depends: A
          - name: D
            template: nested-diamond
            arguments:
              parameters:
                - name: message
                  value: D
            depends: B && C
    - name: nested-diamond
      inputs:
        parameters:
          - name: message
      outputs: {}
      metadata: {}
      dag:
        tasks:
          - name: A
            template: echo
            arguments:
              parameters:
                - name: message
                  value: '{{inputs.parameters.message}}A'
          - name: B
            template: echo
            arguments:
              parameters:
                - name: message
                  value: '{{inputs.parameters.message}}B'
            depends: A
          - name: C
            template: echo
            arguments:
              parameters:
                - name: message
                  value: '{{inputs.parameters.message}}C'
            depends: A
          - name: D
            template: echo
            arguments:
              parameters:
                - name: message
                  value: '{{inputs.parameters.message}}D'
            depends: B && C
  entrypoint: diamond
  arguments: {}
status:
  phase: Succeeded
  startedAt: '2024-03-14T09:06:43Z'
  finishedAt: '2024-03-14T09:09:22Z'
  progress: 16/16
  nodes:
    dag-nested-m5kw8:
      id: dag-nested-m5kw8
      name: dag-nested-m5kw8
      displayName: dag-nested-m5kw8
      type: DAG
      templateName: diamond
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      startedAt: '2024-03-14T09:06:43Z'
      finishedAt: '2024-03-14T09:09:22Z'
      progress: 16/16
      resourcesDuration:
        cpu: 0
        memory: 47
      children:
        - dag-nested-m5kw8-3850982129
      outboundNodes:
        - dag-nested-m5kw8-3608240664
    dag-nested-m5kw8-2008278176:
      id: dag-nested-m5kw8-2008278176
      name: dag-nested-m5kw8.B.B
      displayName: B
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3800649272
      startedAt: '2024-03-14T09:08:22Z'
      finishedAt: '2024-03-14T09:08:28Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: BB
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-2008278176/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-2108943890
      hostNodeName: minikube
    dag-nested-m5kw8-2025055795:
      id: dag-nested-m5kw8-2025055795
      name: dag-nested-m5kw8.B.C
      displayName: C
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3800649272
      startedAt: '2024-03-14T09:08:22Z'
      finishedAt: '2024-03-14T09:08:28Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 3
      inputs:
        parameters:
          - name: message
            value: BC
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-2025055795/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-2108943890
      hostNodeName: minikube
    dag-nested-m5kw8-2058611033:
      id: dag-nested-m5kw8-2058611033
      name: dag-nested-m5kw8.B.A
      displayName: A
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3800649272
      startedAt: '2024-03-14T09:08:12Z'
      finishedAt: '2024-03-14T09:08:17Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: BA
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-2058611033/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-2008278176
        - dag-nested-m5kw8-2025055795
      hostNodeName: minikube
    dag-nested-m5kw8-2108943890:
      id: dag-nested-m5kw8-2108943890
      name: dag-nested-m5kw8.B.D
      displayName: D
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3800649272
      startedAt: '2024-03-14T09:08:32Z'
      finishedAt: '2024-03-14T09:08:37Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: BD
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-2108943890/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-3901314986
      hostNodeName: minikube
    dag-nested-m5kw8-2458886635:
      id: dag-nested-m5kw8-2458886635
      name: dag-nested-m5kw8.A.D
      displayName: D
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3850982129
      startedAt: '2024-03-14T09:08:02Z'
      finishedAt: '2024-03-14T09:08:06Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 3
      inputs:
        parameters:
          - name: message
            value: AD
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-2458886635/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-3800649272
        - dag-nested-m5kw8-3817426891
      hostNodeName: minikube
    dag-nested-m5kw8-2509219492:
      id: dag-nested-m5kw8-2509219492
      name: dag-nested-m5kw8.A.A
      displayName: A
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3850982129
      startedAt: '2024-03-14T09:06:43Z'
      finishedAt: '2024-03-14T09:07:44Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 17
      inputs:
        parameters:
          - name: message
            value: AA
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-2509219492/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-2559552349
        - dag-nested-m5kw8-2542774730
      hostNodeName: minikube
    dag-nested-m5kw8-2542774730:
      id: dag-nested-m5kw8-2542774730
      name: dag-nested-m5kw8.A.C
      displayName: C
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3850982129
      startedAt: '2024-03-14T09:07:52Z'
      finishedAt: '2024-03-14T09:07:56Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: AC
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-2542774730/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-2458886635
      hostNodeName: minikube
    dag-nested-m5kw8-2559552349:
      id: dag-nested-m5kw8-2559552349
      name: dag-nested-m5kw8.A.B
      displayName: B
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3850982129
      startedAt: '2024-03-14T09:07:52Z'
      finishedAt: '2024-03-14T09:07:56Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: AB
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-2559552349/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-2458886635
      hostNodeName: minikube
    dag-nested-m5kw8-3608240664:
      id: dag-nested-m5kw8-3608240664
      name: dag-nested-m5kw8.D.D
      displayName: D
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3901314986
      startedAt: '2024-03-14T09:09:12Z'
      finishedAt: '2024-03-14T09:09:17Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: DD
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-3608240664/main.log
        exitCode: '0'
      hostNodeName: minikube
    dag-nested-m5kw8-3692128759:
      id: dag-nested-m5kw8-3692128759
      name: dag-nested-m5kw8.D.A
      displayName: A
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3901314986
      startedAt: '2024-03-14T09:08:52Z'
      finishedAt: '2024-03-14T09:08:56Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: DA
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-3692128759/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-3708906378
        - dag-nested-m5kw8-3725683997
      hostNodeName: minikube
    dag-nested-m5kw8-3708906378:
      id: dag-nested-m5kw8-3708906378
      name: dag-nested-m5kw8.D.B
      displayName: B
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3901314986
      startedAt: '2024-03-14T09:09:02Z'
      finishedAt: '2024-03-14T09:09:07Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: DB
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-3708906378/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-3608240664
      hostNodeName: minikube
    dag-nested-m5kw8-3725683997:
      id: dag-nested-m5kw8-3725683997
      name: dag-nested-m5kw8.D.C
      displayName: C
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3901314986
      startedAt: '2024-03-14T09:09:02Z'
      finishedAt: '2024-03-14T09:09:07Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: DC
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-3725683997/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-3608240664
      hostNodeName: minikube
    dag-nested-m5kw8-3800649272:
      id: dag-nested-m5kw8-3800649272
      name: dag-nested-m5kw8.B
      displayName: B
      type: DAG
      templateName: nested-diamond
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8
      startedAt: '2024-03-14T09:08:12Z'
      finishedAt: '2024-03-14T09:08:42Z'
      progress: 8/8
      resourcesDuration:
        cpu: 0
        memory: 17
      inputs:
        parameters:
          - name: message
            value: B
      children:
        - dag-nested-m5kw8-2058611033
      outboundNodes:
        - dag-nested-m5kw8-2108943890
    dag-nested-m5kw8-3817426891:
      id: dag-nested-m5kw8-3817426891
      name: dag-nested-m5kw8.C
      displayName: C
      type: DAG
      templateName: nested-diamond
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8
      startedAt: '2024-03-14T09:08:12Z'
      finishedAt: '2024-03-14T09:08:52Z'
      progress: 8/8
      resourcesDuration:
        cpu: 0
        memory: 14
      inputs:
        parameters:
          - name: message
            value: C
      children:
        - dag-nested-m5kw8-539918490
      outboundNodes:
        - dag-nested-m5kw8-489585633
    dag-nested-m5kw8-3850982129:
      id: dag-nested-m5kw8-3850982129
      name: dag-nested-m5kw8.A
      displayName: A
      type: DAG
      templateName: nested-diamond
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8
      startedAt: '2024-03-14T09:06:43Z'
      finishedAt: '2024-03-14T09:08:12Z'
      progress: 16/16
      resourcesDuration:
        cpu: 0
        memory: 47
      inputs:
        parameters:
          - name: message
            value: A
      children:
        - dag-nested-m5kw8-2509219492
      outboundNodes:
        - dag-nested-m5kw8-2458886635
    dag-nested-m5kw8-3901314986:
      id: dag-nested-m5kw8-3901314986
      name: dag-nested-m5kw8.D
      displayName: D
      type: DAG
      templateName: nested-diamond
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8
      startedAt: '2024-03-14T09:08:52Z'
      finishedAt: '2024-03-14T09:09:22Z'
      progress: 4/4
      resourcesDuration:
        cpu: 0
        memory: 8
      inputs:
        parameters:
          - name: message
            value: D
      children:
        - dag-nested-m5kw8-3692128759
      outboundNodes:
        - dag-nested-m5kw8-3608240664
    dag-nested-m5kw8-489585633:
      id: dag-nested-m5kw8-489585633
      name: dag-nested-m5kw8.C.D
      displayName: D
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3817426891
      startedAt: '2024-03-14T09:08:42Z'
      finishedAt: '2024-03-14T09:08:45Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 0
      inputs:
        parameters:
          - name: message
            value: CD
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-489585633/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-3901314986
      hostNodeName: minikube
    dag-nested-m5kw8-506363252:
      id: dag-nested-m5kw8-506363252
      name: dag-nested-m5kw8.C.C
      displayName: C
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3817426891
      startedAt: '2024-03-14T09:08:22Z'
      finishedAt: '2024-03-14T09:08:30Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: CC
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-506363252/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-489585633
      hostNodeName: minikube
    dag-nested-m5kw8-523140871:
      id: dag-nested-m5kw8-523140871
      name: dag-nested-m5kw8.C.B
      displayName: B
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3817426891
      startedAt: '2024-03-14T09:08:22Z'
      finishedAt: '2024-03-14T09:08:30Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: CB
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-523140871/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-489585633
      hostNodeName: minikube
    dag-nested-m5kw8-539918490:
      id: dag-nested-m5kw8-539918490
      name: dag-nested-m5kw8.C.A
      displayName: A
      type: Pod
      templateName: echo
      templateScope: local/dag-nested-m5kw8
      phase: Succeeded
      boundaryID: dag-nested-m5kw8-3817426891
      startedAt: '2024-03-14T09:08:12Z'
      finishedAt: '2024-03-14T09:08:17Z'
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 2
      inputs:
        parameters:
          - name: message
            value: CA
      outputs:
        artifacts:
          - name: main-logs
            s3:
              key: dag-nested-m5kw8/dag-nested-m5kw8-echo-539918490/main.log
        exitCode: '0'
      children:
        - dag-nested-m5kw8-506363252
        - dag-nested-m5kw8-523140871
      hostNodeName: minikube
  conditions:
    - type: PodRunning
      status: 'False'
    - type: Completed
      status: 'True'
  resourcesDuration:
    cpu: 0
    memory: 47
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default-v1
    namespace: argo
    artifactRepository:
      archiveLogs: true
      s3:
        endpoint: 'minio:9000'
        bucket: my-bucket
        insecure: true
        accessKeySecret:
          name: my-minio-cred
          key: accesskey
        secretKeySecret:
          name: my-minio-cred
          key: secretkey
